Repository SSL-Roots/consai_ros2, pull requests merged in 2023-05, with the labels that each got.

#72 grSimのロボットをON/OFFできるボタンをVisualizerに追加
  consai_visualizer/resource/visualizer.ui
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: enhancement

#73 field_observerのユニットテスト追加とget_receiver_robots_idの修正
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/field_observer.py
  consai_examples/tests/test_field_observer.py
  consai_examples/tests/tracked_frame_publisher.py
Labels: bug

#75 サブアタッカーが、ボールプレースメントでボールを受取り続けるように修正
  consai_examples/consai_examples/decisions/sub_attacker.py
Labels: enhancement

#78 ロボット台数とカードのフォントを大きくした
  consai_visualizer/resource/visualizer.ui
Labels: enhancement

#81 ペナルティ後に相手ディフェンスエリアに侵入しないように、待機位置を変更した
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/center_back1.py
  consai_examples/consai_examples/decisions/center_back2.py
  consai_examples/consai_examples/decisions/decision_base.py
  consai_examples/consai_examples/decisions/side_back1.py
  consai_examples/consai_examples/decisions/side_back2.py
  consai_examples/consai_examples/decisions/sub_attacker.py
  consai_examples/consai_examples/decisions/zone_defense.py
Labels: enhancement

#85 ペナルティーマークを描画
  consai_visualizer/src/consai_visualizer/field_widget.py
Labels: enhancement

#88 最終移動目標姿勢をfinal_goal_poseとしてpublishする。それを描画する
  consai_robot_controller/include/consai_robot_controller/controller_component.hpp
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: enhancement

#87 ロボットの位置・速度をリストからPose2Dに変更とIDをコールバック関数で取得に変更
  consai_examples/consai_examples/field_observer.py
  consai_examples/consai_examples/geometry_tools.py
  consai_examples/tests/test_geometry_tools.py
Labels: bug, enhancement

#90 goal_poses型を作って、goal_poseとfinal_goal_poseを集約した
  consai_msgs/CMakeLists.txt
  consai_msgs/msg/GoalPoses.msg
  consai_robot_controller/include/consai_robot_controller/controller_component.hpp
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: enhancement

#94 grSimのボールを動かすとき、ボールが弾け飛ぶのを解決する
  consai_visualizer/src/consai_visualizer/field_widget.py
Labels: enhancement

#93 refere_parserにforce_startフラグを追加
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/referee_parser.py
Labels: bug

#91 パス関数でシュートコースの候補も出せるように変更
  consai_examples/consai_examples/decisions/goalie.py
  consai_examples/consai_examples/field_observer.py
  consai_examples/tests/test_field_observer.py
Labels: enhancement

#97 ビジュアライザがサイド反転に対応
  consai_robot_controller/launch/test.launch.py
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: enhancement

#96 Fix pass func error
  consai_examples/consai_examples/field_observer.py
Labels: bug

#98 visualizerロボット台数を表示する
  consai_visualizer/resource/visualizer.ui
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: enhancement

#95 control_ballアルゴリズム変更、変数をROSパラメータ化
  consai_robot_controller/config/control_params.yaml
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/field_info_parser.cpp
Labels: enhancement

#100 キックパワーを弱くした
  consai_robot_controller/src/field_info_parser.cpp
Labels: enhancement

#102 ConstraintLineに交点からのオフセットを追加
  consai_examples/consai_examples/control.py
  consai_examples/consai_examples/robot_operator.py
  consai_msgs/msg/ConstraintLine.msg
  consai_robot_controller/src/field_info_parser.cpp
Labels: enhancement

#105 ボール500mm回避の処理を更新。フィールド外に目標位置を生成しない
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/src/field_info_parser.cpp
Labels: enhancement

#109 ペナルティキックでボールが相手ディフェンスエリアに入ったら、ボールを追いかけない
  consai_examples/consai_examples/decisions/attacker.py
Labels: enhancement

#111 ビジュアライザのリセットタイマーが干渉していたので修正
  consai_visualizer/src/consai_visualizer/visualizer.py
Labels: bug

#119 ament_lint_autoの適用およびコードフォーマットの修正
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/control.py
  consai_examples/consai_examples/control_with_role.py
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/center_back1.py
  consai_examples/consai_examples/decisions/center_back2.py
  consai_examples/consai_examples/decisions/decision_base.py
  consai_examples/consai_examples/decisions/goalie.py
  consai_examples/consai_examples/decisions/side_back1.py
  consai_examples/consai_examples/decisions/side_back2.py
  consai_examples/consai_examples/decisions/side_wing.py
  consai_examples/consai_examples/decisions/sub_attacker.py
  consai_examples/consai_examples/decisions/substitute.py
  consai_examples/consai_examples/decisions/zone_defense.py
  consai_examples/consai_examples/field_observer.py
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/geometry_tools.py
  consai_examples/consai_examples/referee_parser.py
  consai_examples/consai_examples/robot_operator.py
  consai_examples/consai_examples/role_assignment.py
  consai_examples/launch/start.launch.py
  consai_examples/tests/test_field_observer.py
  consai_examples/tests/test_geometry_tools.py
  consai_examples/tests/test_robot_operator.py
  consai_examples/tests/test_role_assignment.py
  consai_examples/tests/tracked_frame_publisher.py
  consai_msgs/CMakeLists.txt
  consai_observer/CMakeLists.txt
  consai_robot_controller/CMakeLists.txt
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/src/control_tools.cpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/test/control_tools_test.cpp
  consai_vision_tracker/CMakeLists.txt
  consai_visualizer/CMakeLists.txt
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer/src/consai_visualizer/referee_parser.py
  consai_visualizer/src/consai_visualizer/visualizer.py
  robocup_ssl_comm/CMakeLists.txt
  robocup_ssl_comm/include/robocup_ssl_comm/multicast.hpp
  robocup_ssl_comm/include/robocup_ssl_comm/udp_sender.hpp
  robocup_ssl_comm/src/game_controller_component.cpp
  robocup_ssl_comm/src/vision_component.cpp
  robocup_ssl_msgs/CMakeLists.txt
Labels: refactoring
