Repository SSL-Roots/consai_ros2, pull requests merged in 2024-04, with the labels that each got.

#202 Action通信をやめて、Topic通信でcontrollerに指令を送る
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/operation.py
  consai_examples/consai_examples/robot_operator.py
  consai_msgs/CMakeLists.txt
  consai_msgs/msg/RobotControlMsg.msg
  consai_robot_controller/include/consai_robot_controller/controller_component.hpp
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/include/consai_robot_controller/obstacle/obstacle_observer.hpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/obstacle/obstacle_observer.cpp
  consai_robot_controller/test/obstacle_observer_test.cpp
  consai_tools/consai_tools/hasher/robot_control_hasher.py
Labels: refactoring, 優先度：高

#203 Refactor field observer
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/center_back1.py
  consai_examples/consai_examples/decisions/center_back2.py
  consai_examples/consai_examples/decisions/decision_base.py
  consai_examples/consai_examples/decisions/goalie.py
  consai_examples/consai_examples/decisions/sub_attacker.py
  consai_examples/consai_examples/decisions/zone_defense.py
  consai_examples/consai_examples/field_observer.py
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/observer/__init__.py
  consai_examples/consai_examples/observer/ball_motion_observer.py
  consai_examples/consai_examples/observer/ball_placement_observer.py
  consai_examples/consai_examples/observer/ball_position_observer.py
  consai_examples/consai_examples/observer/detection_wrapper.py
  consai_examples/consai_examples/observer/pass_shoot_observer.py
  consai_examples/consai_examples/observer/pos_vel.py
  consai_examples/consai_examples/observer/zone_ball_observer.py
  consai_examples/consai_examples/observer/zone_target_observer.py
  consai_examples/consai_examples/robot_operator.py
  consai_examples/tests/test_detection_wrapper.py
  consai_examples/tests/test_field_observer.py
  consai_examples/tests/test_pass_shoot_observer.py
  consai_examples/tests/tracked_frame_wrapper.py
  consai_robot_controller/src/controller_component.cpp
  consai_tools/consai_tools/geometry/geometry_tools.py
  consai_tools/tests/test_geometry_tools.py
Labels: refactoring

#204 Move geometry_tools to consai_tools package.
  consai_robot_controller/CMakeLists.txt
  consai_robot_controller/package.xml
  consai_robot_controller/src/constraint_parser.cpp
  consai_robot_controller/src/controller_component.cpp
  consai_robot_controller/src/tactic/ball_boy_tactics.cpp
  consai_robot_controller/src/tactic/tactic_control_ball.cpp
  consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
  consai_tools/CMakeLists.txt
  consai_tools/include/consai_tools/geometry_tools.hpp
  consai_tools/src/geometry_tools.cpp
  consai_tools/tests/cpp/test_geometry_tools.cpp
Labels: refactoring

#206 Add dribbler tactic
  consai_robot_controller/CMakeLists.txt
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/dribble_tactics.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/dribble_tactics.cpp
  consai_tools/include/consai_tools/geometry_tools.hpp
  consai_tools/src/geometry_tools.cpp
Labels: スキル

#207 Add shoot_tactics
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/observer/pass_shoot_observer.py
  consai_robot_controller/CMakeLists.txt
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/shoot_tactics.cpp
  consai_tools/include/consai_tools/geometry_tools.hpp
  consai_tools/src/geometry_tools.cpp
  tests/test_scenario_ball_placement.py
Labels: スキル

#211 Update setplay motion.
  consai_examples/consai_examples/decisions/attacker.py
  consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/shoot_tactics.cpp
  tests/test_scenario_ball_placement.py
Labels: スキル

#218 Update role priority
  consai_examples/consai_examples/role_assignment.py
  consai_examples/tests/test_role_assignment.py
Labels: ゲーム戦略

#224 Switch ball system model of KF when ball is far from robots.
  consai_tools/include/consai_tools/geometry_tools.hpp
  consai_tools/src/geometry_tools.cpp
  consai_vision_tracker/CMakeLists.txt
  consai_vision_tracker/include/consai_vision_tracker/ball_tracker.hpp
  consai_vision_tracker/include/consai_vision_tracker/robot_tracker.hpp
  consai_vision_tracker/package.xml
  consai_vision_tracker/src/ball_tracker.cpp
  consai_vision_tracker/src/tracker_component.cpp
Labels: 優先度：高

#226 Fix ball approach
  consai_robot_controller/src/tactic/dribble_tactics.cpp
  consai_robot_controller/src/tactic/shoot_tactics.cpp
Labels: スキル

#228 ロボットのカルマンフィルタに誘拐対策を実装。シナリオテストでできるだけ全ロボットを使用する。
  consai_vision_tracker/include/consai_vision_tracker/robot_tracker.hpp
  consai_vision_tracker/src/robot_tracker.cpp
  tests/test_scenario_ball_placement.py
  tests/test_scenario_force_start.py
  tests/test_scenario_free_kick.py
  tests/test_scenario_kickoff.py
  tests/test_scenario_penalty.py
  tests/test_scenario_stop.py
  tests/yellow_invert/test_scenario_yellow_invert_kickoff.py
Labels: Vision

#216 Disable stop velocity at non STOP signal called.
  consai_examples/consai_examples/game.py
Labels: スキル

#231 ディフェンスエリア回避の追加
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/goalie.py
  consai_examples/consai_examples/operation.py
  consai_msgs/msg/RobotControlMsg.msg
  consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
  consai_tools/include/consai_tools/geometry_tools.hpp
  consai_tools/src/geometry_tools.cpp
  consai_tools/tests/cpp/test_geometry_tools.cpp
  tests/test_scenario_obstacle_avoidance.py
Labels: 優先度：高, スキル

#233 シュート関連のパラメータ更新
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/operation.py
  consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp
  consai_robot_controller/src/tactic/shoot_tactics.cpp
Labels: スキル

#235 disable avoid_defense_area at ball_placement
  consai_examples/consai_examples/decisions/attacker.py
  tests/test_scenario_ball_placement.py
Labels: bug

#237 Dribbling at our penalty shoot
  consai_examples/consai_examples/decisions/attacker.py
  tests/test_scenario_penalty.py
Labels: スキル

#238 Change ball placement default position to STOP position. Update shoot tactic to pass scenario_test.
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/center_back.py
  consai_examples/consai_examples/decisions/side_back.py
  consai_examples/consai_examples/decisions/sub_attacker.py
  consai_examples/consai_examples/decisions/zone_defense.py
  consai_robot_controller/src/tactic/shoot_tactics.cpp
Labels: ゲーム戦略

#239 Remove center back 1 and 2
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/decisions/center_back1.py
  consai_examples/consai_examples/decisions/center_back2.py
Labels: refactoring

#240 Visualize role
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/role_assignment.py
  consai_examples/consai_examples/role_to_visualize_msg.py
  consai_visualizer/src/consai_visualizer/field_widget.py
  consai_visualizer_msgs/CMakeLists.txt
  consai_visualizer_msgs/msg/Objects.msg
  consai_visualizer_msgs/msg/ShapeText.msg
  tests/test_scenario_penalty.py
Labels: Vision

#250 Set max priority for defense area avoidance
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
Labels: 衝突回避

#249 Add man mark observer
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/field_observer.py
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/observer/man_mark_observer.py
  consai_examples/consai_examples/role_to_visualize_msg.py
Labels: ゲーム戦略

#252 センターバックがお互いを衝突回避しない。
  consai_examples/consai_examples/decisions/center_back.py
  consai_examples/consai_examples/operation.py
  consai_msgs/msg/RobotControlMsg.msg
  consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
Labels: 衝突回避

#243 Use ball trajectory for attacker role assignment
  consai_examples/CMakeLists.txt
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/role_assignment.py
  consai_examples/consai_examples/role_to_visualize_msg.py
Labels: ゲーム戦略

#260 Add motion_test for control py
  consai_examples/consai_examples/observer/man_mark_observer.py
  consai_examples/consai_examples/observer/side_back_target_observer.py
  consai_examples/consai_examples/observer/zone_man_mark_target_observer.py
  consai_examples/consai_examples/operation_test/control.py
Labels: Test

#257 Update shoot tactic to go forward at shooting
  consai_robot_controller/src/tactic/shoot_tactics.cpp
Labels: スキル

#261 ゴーリーのディフェンス位置の調整
  consai_examples/consai_examples/decisions/goalie.py
Labels: ゲーム戦略

#266 Add destination_pose method to field_observer
  consai_examples/consai_examples/field_observer.py
  consai_robot_controller/include/consai_robot_controller/controller_component.hpp
  consai_robot_controller/src/controller_component.cpp
Labels: ゲーム戦略

#255 キックオフ時のパスを実装
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/decisions/decision_base.py
  consai_examples/consai_examples/game.py
  consai_examples/consai_examples/referee_parser.py
Labels: ゲーム戦略

#273 敵ロボット位置のキー検索を変更（ゴーリー）
  consai_examples/consai_examples/decisions/goalie.py
Labels: bug

#275 Use back dribble for ball_placement
  consai_examples/consai_examples/decisions/attacker.py
  consai_examples/consai_examples/operation.py
  consai_msgs/msg/RobotControlMsg.msg
  consai_robot_controller/CMakeLists.txt
  consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
  consai_robot_controller/include/consai_robot_controller/tactic/back_dribble_tactics.hpp
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/back_dribble_tactics.cpp
Labels: スキル

#279 ディフェンスエリアにあるボールクリアを以前の動作に戻した
  consai_examples/consai_examples/decisions/goalie.py
  consai_examples/consai_examples/observer/pass_shoot_observer.py
Labels: bug

#269 update defense_area avoidance
  consai_robot_controller/src/field_info_parser.cpp
  consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
  tests/test_scenario_obstacle_avoidance.py
Labels: 衝突回避

#272 キックオフのときに対角へ移動して相手の邪魔をできるようにした
  consai_examples/consai_examples/decisions/attacker.py
Labels: 優先度：低, ゲーム戦略

#300 アタッカーの行動生成の方法をフラグで管理
  consai_examples/consai_examples/decisions/attacker.py
Labels: bug, ゲーム戦略

#301 デフォルトの加速度を変更
  consai_robot_controller/config/control_params.yaml
Labels: スキル
